version: '3.1'
services:
  db:
#    image: postgres:10
    build: ./dockerfile/
    restart: always
    container_name: library
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
