version: '3.1'
services:
  postgres:
#    image: postgres:10
    build: ./dockerfile/
    restart: always
    container_name: library
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres

  elasticsearch:
    image: elasticsearch
    container_name: search
    ports:
    - "9200:9200"
